#!/usr/bin/env bash
# This script displays specific fields from /etc/passwd using a while loop

while IFS=: read -r username _ uid _ _ home _; do
    echo "$username"
    echo "$uid"
    echo "$home"
done < /etc/passwd
