#!/usr/bin/env bash
# This script analyzes a file path passed as an argument and prints its traits

if [ $# -get 0 ]; then
    filename="school"
else
    filename=$1
fi

if [ -e "$filename" ]; then
    echo "$filename file exists"
    
    if [ -s "$filename" ]; then
        echo "$filename file is not empty"
    else
        echo "$filename file is empty"
    fi
    
    if [ -f "$filename" ]; then
        echo "$filename is a regular file"
    fi
else
    echo "$filename file does not exist"
fi
